import 'locale_controller.dart';

String tr(String key) {
  final map = localeController.isArabic ? _ar : _en;
  return map[key] ?? _en[key] ?? key;
}

const Map<String, String> _en = {
  // Common
  'appName': 'Eyan',
  'appTagline': 'Your Health Companion',
  'next': 'Next',
  'back': 'Back',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'save': 'Save',
  'seeAll': 'See all',
  'search': 'Search',
  'egp': 'EGP',
  'today': 'Today',
  'tomorrow': 'Tomorrow',
  'close': 'Close',
  'comingSoon': 'Coming soon',
  'edit': 'Edit',
  'bookNow': 'Book',

  // Auth
  'welcomeBack': 'Welcome Back',
  'loginSubtitle': 'Please login to your account',
  'email': 'Email',
  'password': 'Password',
  'rememberMe': 'Remember me',
  'forgotPassword': 'Forgot Password?',
  'orContinueWith': 'or continue with',
  'google': 'Google',
  'apple': 'Apple',
  'noAccount': "Don't have an account? ",
  'signUp': 'Sign Up',
  'createAccount': 'Create Account',
  'registerSubtitle': 'Please sign up to get started',
  'fullName': 'Full Name',
  'phoneNumber': 'Phone Number',
  'confirmPassword': 'Confirm Password',
  'alreadyHaveAccount': 'Already have an account? ',
  'login': 'Login',
  'enterEmail': 'Enter email',
  'invalidEmail': 'Invalid email',
  'enterPassword': 'Enter password',
  'minChars': 'Min 6 chars',
  'enterName': 'Enter your name',
  'enterPhone': 'Enter phone',
  'confirmPasswordHint': 'Confirm password',
  'passwordsNoMatch': 'Passwords do not match',

  // Nav
  'navHome': 'Home',
  'navAppointments': 'Appointments',
  'navChat': 'Chat',
  'navProfile': 'Profile',

  // Home
  'helloThere': 'Hello 👋',
  'findYourDoctor': 'Find your doctor',
  'searchHint': 'Search doctor, specialty...',
  'specialties': 'Specialties',
  'upcomingAppointment': 'Upcoming appointment',
  'topDoctors': 'Top doctors',
  'allClinics': 'All clinics',
  'doctorsFound': 'doctors found',
  'noResults': 'No doctors found',
  'reminderIn': 'in',

  // Doctor card / detail
  'drPrefix': 'Dr.',
  'reviews': 'reviews',
  'perVisit': '/ visit',
  'nextAvailable': 'Next available',
  'about': 'About',
  'workingHours': 'Working hours',
  'selectDate': 'Select date',
  'availableSlots': 'Available time slots',
  'noSlotsAvailable': 'No slots available on this day',
  'patients': 'Patients',
  'experience': 'Experience',
  'years': 'years',
  'bookAppointment': 'Book Appointment',
  'consultationFee': 'Consultation fee',
  'clinicAddress': 'Clinic address',

  // Booking
  'confirmBooking': 'Confirm Booking',
  'appointmentWith': 'Appointment with',
  'date': 'Date',
  'time': 'Time',
  'clinic': 'Clinic',
  'fee': 'Fee',
  'confirmAndBook': 'Confirm Booking',
  'bookingSuccess': 'Booking Confirmed!',
  'bookingSuccessMsg': 'Your appointment has been booked successfully. We will remind you before it starts.',
  'viewAppointment': 'View Appointment',
  'backToHome': 'Back to Home',

  // Appointments
  'myAppointments': 'My Appointments',
  'upcoming': 'Upcoming',
  'past': 'Past',
  'noUpcoming': 'No upcoming appointments',
  'noPast': 'No past appointments yet',
  'yourNextVisit': 'Your next visit',
  'startsIn': 'Starts in',
  'daysShort': 'd',
  'hoursShort': 'h',
  'minutesShort': 'm',
  'appointmentDetails': 'Appointment Details',
  'cancelAppointment': 'Cancel Appointment',
  'rescheduleAppointment': 'Reschedule',
  'addToCalendar': 'Add to calendar',
  'statusConfirmed': 'Confirmed',
  'statusCompleted': 'Completed',
  'statusCancelled': 'Cancelled',
  'bookingRef': 'Booking ref',
  'cancelConfirmTitle': 'Cancel this appointment?',
  'cancelConfirmMsg': "This action can't be undone. You can book a new appointment anytime.",
  'keepIt': 'Keep it',
  'yesCancel': 'Yes, Cancel',

  // Prescriptions
  'myPrescriptions': 'My Prescriptions',
  'prescribedBy': 'Prescribed by',
  'medicines': 'Medicines',
  'dosage': 'Dosage',
  'duration': 'Duration',
  'frequency': 'Frequency',
  'doctorNotes': "Doctor's notes",
  'noPrescriptions': 'No prescriptions yet',
  'prescriptionDetails': 'Prescription Details',
  'shareDownload': 'Share / Download',
  'diagnosis': 'Diagnosis',

  // Chat
  'messages': 'Messages',
  'typeMessage': 'Type a message...',
  'online': 'Online',
  'noMessages': 'No conversations yet',
  'startChat': 'Book an appointment to start chatting with your doctor',

  // Profile
  'myProfile': 'My Profile',
  'editProfile': 'Edit profile',
  'language': 'Language',
  'arabic': 'العربية',
  'english': 'English',
  'medicalRecords': 'Medical records',
  'notifications': 'Notifications',
  'settings': 'Settings',
  'helpSupport': 'Help & support',
  'logout': 'Log out',
  'version': 'Version',

  // Specialties
  'specGeneral': 'General',
  'specDentist': 'Dentist',
  'specCardiologist': 'Cardiologist',
  'specDermatologist': 'Dermatologist',
  'specPediatrician': 'Pediatrician',
  'specOrthopedic': 'Orthopedic',
  'specENT': 'ENT',
  'specOphthalmologist': 'Ophthalmologist',
  'specNeurologist': 'Neurologist',
  'specGynecologist': 'Gynecologist',
};

const Map<String, String> _ar = {
  // Common
  'appName': 'عيان',
  'appTagline': 'رفيقك الصحي',
  'next': 'التالي',
  'back': 'رجوع',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'save': 'حفظ',
  'seeAll': 'عرض الكل',
  'search': 'بحث',
  'egp': 'ج.م',
  'today': 'اليوم',
  'tomorrow': 'بكرة',
  'close': 'إغلاق',
  'comingSoon': 'قريبًا',
  'edit': 'تعديل',
  'bookNow': 'احجز',

  // Auth
  'welcomeBack': 'أهلاً بعودتك',
  'loginSubtitle': 'سجّل دخولك لمتابعة حجوزاتك',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'rememberMe': 'تذكرني',
  'forgotPassword': 'نسيت كلمة المرور؟',
  'orContinueWith': 'أو تابع باستخدام',
  'google': 'جوجل',
  'apple': 'أبل',
  'noAccount': 'مفيش حساب لسه؟ ',
  'signUp': 'إنشاء حساب',
  'createAccount': 'إنشاء حساب جديد',
  'registerSubtitle': 'سجّل بياناتك عشان تبدأ',
  'fullName': 'الاسم بالكامل',
  'phoneNumber': 'رقم الموبايل',
  'confirmPassword': 'تأكيد كلمة المرور',
  'alreadyHaveAccount': 'عندك حساب بالفعل؟ ',
  'login': 'تسجيل الدخول',
  'enterEmail': 'اكتب البريد الإلكتروني',
  'invalidEmail': 'البريد الإلكتروني غير صحيح',
  'enterPassword': 'اكتب كلمة المرور',
  'minChars': '6 حروف على الأقل',
  'enterName': 'اكتب اسمك',
  'enterPhone': 'اكتب رقم الموبايل',
  'confirmPasswordHint': 'أكّد كلمة المرور',
  'passwordsNoMatch': 'كلمتا المرور غير متطابقتين',

  // Nav
  'navHome': 'الرئيسية',
  'navAppointments': 'مواعيدي',
  'navChat': 'المحادثات',
  'navProfile': 'حسابي',

  // Home
  'helloThere': 'أهلاً بيك 👋',
  'findYourDoctor': 'دوّر على دكتورك',
  'searchHint': 'دور باسم الدكتور أو التخصص...',
  'specialties': 'التخصصات',
  'upcomingAppointment': 'معادك الجاي',
  'topDoctors': 'أفضل الدكاترة',
  'allClinics': 'كل العيادات',
  'doctorsFound': 'دكتور متاح',
  'noResults': 'مفيش نتايج',
  'reminderIn': 'خلال',

  // Doctor card / detail
  'drPrefix': 'د.',
  'reviews': 'تقييم',
  'perVisit': '/ الكشف',
  'nextAvailable': 'أقرب معاد',
  'about': 'نبذة',
  'workingHours': 'مواعيد العيادة',
  'selectDate': 'اختار اليوم',
  'availableSlots': 'المواعيد المتاحة',
  'noSlotsAvailable': 'مفيش مواعيد متاحة في اليوم ده',
  'patients': 'المرضى',
  'experience': 'الخبرة',
  'years': 'سنة',
  'bookAppointment': 'احجز المعاد',
  'consultationFee': 'سعر الكشف',
  'clinicAddress': 'عنوان العيادة',

  // Booking
  'confirmBooking': 'تأكيد الحجز',
  'appointmentWith': 'معاد مع',
  'date': 'التاريخ',
  'time': 'الميعاد',
  'clinic': 'العيادة',
  'fee': 'السعر',
  'confirmAndBook': 'تأكيد الحجز',
  'bookingSuccess': 'تم تأكيد الحجز!',
  'bookingSuccessMsg': 'تم حجز معادك بنجاح، وهنفكّرك قبل ميعاده.',
  'viewAppointment': 'عرض الحجز',
  'backToHome': 'العودة للرئيسية',

  // Appointments
  'myAppointments': 'مواعيدي',
  'upcoming': 'القادمة',
  'past': 'السابقة',
  'noUpcoming': 'مفيش مواعيد قادمة',
  'noPast': 'مفيش مواعيد سابقة لسه',
  'yourNextVisit': 'زيارتك الجاية',
  'startsIn': 'هيبدأ خلال',
  'daysShort': 'ي',
  'hoursShort': 'س',
  'minutesShort': 'د',
  'appointmentDetails': 'تفاصيل الحجز',
  'cancelAppointment': 'إلغاء الحجز',
  'rescheduleAppointment': 'تغيير الميعاد',
  'addToCalendar': 'إضافة للتقويم',
  'statusConfirmed': 'مؤكد',
  'statusCompleted': 'تم',
  'statusCancelled': 'ملغي',
  'bookingRef': 'رقم الحجز',
  'cancelConfirmTitle': 'هتلغي المعاد ده؟',
  'cancelConfirmMsg': 'الخطوة دي مينفعش تتراجع فيها، وتقدر تحجز معاد جديد في أي وقت.',
  'keepIt': 'خليه',
  'yesCancel': 'أيوه، إلغاء',

  // Prescriptions
  'myPrescriptions': 'روشتاتي',
  'prescribedBy': 'الروشتة من',
  'medicines': 'الأدوية',
  'dosage': 'الجرعة',
  'duration': 'المدة',
  'frequency': 'عدد المرات',
  'doctorNotes': 'ملاحظات الدكتور',
  'noPrescriptions': 'مفيش روشتات لسه',
  'prescriptionDetails': 'تفاصيل الروشتة',
  'shareDownload': 'مشاركة / تحميل',
  'diagnosis': 'التشخيص',

  // Chat
  'messages': 'المحادثات',
  'typeMessage': 'اكتب رسالة...',
  'online': 'متصل الآن',
  'noMessages': 'مفيش محادثات لسه',
  'startChat': 'احجز معاد عشان تقدر تكلم دكتورك',

  // Profile
  'myProfile': 'حسابي',
  'editProfile': 'تعديل البيانات',
  'language': 'اللغة',
  'arabic': 'العربية',
  'english': 'English',
  'medicalRecords': 'السجل الطبي',
  'notifications': 'الإشعارات',
  'settings': 'الإعدادات',
  'helpSupport': 'المساعدة والدعم',
  'logout': 'تسجيل الخروج',
  'version': 'الإصدار',

  // Specialties
  'specGeneral': 'عام',
  'specDentist': 'أسنان',
  'specCardiologist': 'قلب وأوعية دموية',
  'specDermatologist': 'جلدية',
  'specPediatrician': 'أطفال',
  'specOrthopedic': 'عظام',
  'specENT': 'أنف وأذن وحنجرة',
  'specOphthalmologist': 'عيون',
  'specNeurologist': 'مخ وأعصاب',
  'specGynecologist': 'نساء وتوليد',
};
